name: thad
favicon: null
layout_spectrum: 0.8355445684865117
typography_spectrum: 0.026012837421149015
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3488255806732923
  lightness: 0.9205206718761474
  saturation: 0.7038064375519753
  rhythmicContrast: 0.7280319142155349
purpose: []
